server:
  port: 8761

## Eureka Server Configuration
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: ${EUREKA_HOST:localhost}
    # ip-address: true
    preferIpAddress: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    non-secure-port: 80
    secure-port: 443
  server:
    renewal-percent-threshold: 0.90